name: JavaScript app
on:
  push:
    branches: [ "main" ]
jobs:
  backend-check-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./back
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        version: '24'
        cache: 'npm'
        cache-dependency-path: back/package-lock.json
    - run: npm install
    - run: npm run build --if-present
  backend-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Build x
        uses: docker/setup-buildx-action@v3
      - name: Build and push app
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: doc12mp/mysql_app:js_back
          context: "{{defaultContext}}:back"
  frontend-check-code:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
          working-directory: ./frontend
      steps:
        - name: Check out repository code
          uses: actions/checkout@v5
  frontend-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Build x
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: doc12mp/mysql_app:js_front
          context: "{{defaultContext}}:front"
      - name: Build and push nginx proxy
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: doc12mp/mysql_app:js_nginx
          context: "{{defaultContext}}:front/nginx"
